#############################################################################
# Makefile for building: LIC.app/Contents/MacOS/LIC
# Generated by qmake (3.1) (Qt 6.9.0)
# Project:  LIC.pro
# Template: app
# Command: /Users/shimaron/Qt/6.9.0/macos/bin/qmake -o Makefile LIC.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = @echo compiling $< && /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = @echo compiling $< && /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DISABLE_DEPRECATED_BEFORE=0x060800 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -Isrc -Ishared -I../../../Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers -I../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers -I../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers -Ibuild -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/6.9.0/macos/mkspecs/macx-clang -F/Users/shimaron/Qt/6.9.0/macos/lib
QMAKE         = /Users/shimaron/Qt/6.9.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/shimaron/Qt/6.9.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/shimaron/Qt/6.9.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LIC1.0.0
DISTDIR = /Users/shimaron/Documents/GitHub/LIC/build/LIC1.0.0
LINK          = @echo linking $@ && /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/shimaron/Qt/6.9.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/shimaron/Qt/6.9.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtXml -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = shared/CallTracer.cpp \
		shared/MessageLogger.cpp \
		shared/StringHelper.cpp \
		src/AbstractFunction.cpp \
		src/Function_Constant.cpp \
		src/Function_Cos.cpp \
		src/Function_Difference.cpp \
		src/Function_Exp.cpp \
		src/Function_Exponent.cpp \
		src/Function_Log.cpp \
		src/Function_Product.cpp \
		src/Function_Quotient.cpp \
		src/Function_Sign.cpp \
		src/Function_Sin.cpp \
		src/Function_Sqrt.cpp \
		src/Function_Sum.cpp \
		src/Function_Tan.cpp \
		src/Function_Variable.cpp \
		src/LIC.cpp \
		src/main.cpp build/moc_CallTracer.cpp \
		build/moc_MessageLogger.cpp \
		build/moc_StringHelper.cpp \
		build/moc_AbstractFunction.cpp
OBJECTS       = build/CallTracer.o \
		build/MessageLogger.o \
		build/StringHelper.o \
		build/AbstractFunction.o \
		build/Function_Constant.o \
		build/Function_Cos.o \
		build/Function_Difference.o \
		build/Function_Exp.o \
		build/Function_Exponent.o \
		build/Function_Log.o \
		build/Function_Product.o \
		build/Function_Quotient.o \
		build/Function_Sign.o \
		build/Function_Sin.o \
		build/Function_Sqrt.o \
		build/Function_Sum.o \
		build/Function_Tan.o \
		build/Function_Variable.o \
		build/LIC.o \
		build/main.o \
		build/moc_CallTracer.o \
		build/moc_MessageLogger.o \
		build/moc_StringHelper.o \
		build/moc_AbstractFunction.o
DIST          = ../../../Qt/6.9.0/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.9.0/macos/mkspecs/common/unix.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/mac.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/macx.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/clang.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.9.0/macos/mkspecs/qconfig.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.9.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/6.9.0/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/qt.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/resources.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/moc.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/uic.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/lex.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/silent.prf \
		LIC.pro shared/CallTracer.h \
		shared/MessageLogger.h \
		shared/StringHelper.h \
		src/AbstractFunction.h \
		src/Deploy.h \
		src/Function_Constant.h \
		src/Function_Cos.h \
		src/Function_Difference.h \
		src/Function_Exp.h \
		src/Function_Exponent.h \
		src/Function_Log.h \
		src/Function_Product.h \
		src/Function_Quotient.h \
		src/Function_Sign.h \
		src/Function_Sin.h \
		src/Function_Sqrt.h \
		src/Function_Sum.h \
		src/Function_Tan.h \
		src/Function_Variable.h \
		src/LIC.h \
		src/Macros.h shared/CallTracer.cpp \
		shared/MessageLogger.cpp \
		shared/StringHelper.cpp \
		src/AbstractFunction.cpp \
		src/Function_Constant.cpp \
		src/Function_Cos.cpp \
		src/Function_Difference.cpp \
		src/Function_Exp.cpp \
		src/Function_Exponent.cpp \
		src/Function_Log.cpp \
		src/Function_Product.cpp \
		src/Function_Quotient.cpp \
		src/Function_Sign.cpp \
		src/Function_Sin.cpp \
		src/Function_Sqrt.cpp \
		src/Function_Sum.cpp \
		src/Function_Tan.cpp \
		src/Function_Variable.cpp \
		src/LIC.cpp \
		src/main.cpp
QMAKE_TARGET  = LIC
DESTDIR       = 
TARGET        = LIC.app/Contents/MacOS/LIC

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/shimaron/Documents/GitHub/LIC/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/shimaron/Documents/GitHub/LIC/LIC.pro


include /Users/shimaron/Qt/6.9.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

LIC.app/Contents/MacOS/LIC:  $(OBJECTS)  
	@test -d LIC.app/Contents/MacOS/ || mkdir -p LIC.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LIC.pro ../../../Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.9.0/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.9.0/macos/mkspecs/common/unix.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/mac.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/macx.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/clang.conf \
		../../../Qt/6.9.0/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.9.0/macos/mkspecs/qconfig.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.9.0/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.9.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/6.9.0/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/qt.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/resources.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/moc.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/uic.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/lex.prf \
		../../../Qt/6.9.0/macos/mkspecs/features/silent.prf \
		LIC.pro \
		../../../Qt/6.9.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Resources/QtXml.prl \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile LIC.pro
../../../Qt/6.9.0/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.9.0/macos/mkspecs/features/device_config.prf:
../../../Qt/6.9.0/macos/mkspecs/common/unix.conf:
../../../Qt/6.9.0/macos/mkspecs/common/mac.conf:
../../../Qt/6.9.0/macos/mkspecs/common/macx.conf:
../../../Qt/6.9.0/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.9.0/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.9.0/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.9.0/macos/mkspecs/common/clang.conf:
../../../Qt/6.9.0/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.9.0/macos/mkspecs/qconfig.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdf.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlformat_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testinternals_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../Qt/6.9.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../Qt/6.9.0/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.9.0/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.9.0/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.9.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/6.9.0/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.9.0/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.9.0/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.9.0/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.9.0/macos/mkspecs/features/default_post.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.9.0/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.9.0/macos/mkspecs/features/permissions.prf:
../../../Qt/6.9.0/macos/mkspecs/features/qt.prf:
../../../Qt/6.9.0/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.9.0/macos/mkspecs/features/resources.prf:
../../../Qt/6.9.0/macos/mkspecs/features/moc.prf:
../../../Qt/6.9.0/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.9.0/macos/mkspecs/features/uic.prf:
../../../Qt/6.9.0/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.9.0/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.9.0/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.9.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.9.0/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.9.0/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.9.0/macos/mkspecs/features/yacc.prf:
../../../Qt/6.9.0/macos/mkspecs/features/lex.prf:
../../../Qt/6.9.0/macos/mkspecs/features/silent.prf:
LIC.pro:
../../../Qt/6.9.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.9.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.9.0/macos/lib/QtXml.framework/Resources/QtXml.prl:
../../../Qt/6.9.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile LIC.pro

qmake_all: FORCE

LIC.app/Contents/PkgInfo: 
	@test -d LIC.app/Contents || mkdir -p LIC.app/Contents
	@$(DEL_FILE) LIC.app/Contents/PkgInfo
	@echo "APPL????" > LIC.app/Contents/PkgInfo
LIC.app/Contents/Info.plist: 
	@test -d LIC.app/Contents || mkdir -p LIC.app/Contents
	@$(DEL_FILE) LIC.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../../../Qt/6.9.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.LIC,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.LIC,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,LIC,g" -e "s,@LIBRARY@,LIC,g" -e "s,\$${EXECUTABLE_NAME},LIC,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >LIC.app/Contents/Info.plist

all: Makefile \
		LIC.app/Contents/PkgInfo \
		LIC.app/Contents/Info.plist LIC.app/Contents/MacOS/LIC

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents shared/CallTracer.h shared/MessageLogger.h shared/StringHelper.h src/AbstractFunction.h src/Deploy.h src/Function_Constant.h src/Function_Cos.h src/Function_Difference.h src/Function_Exp.h src/Function_Exponent.h src/Function_Log.h src/Function_Product.h src/Function_Quotient.h src/Function_Sign.h src/Function_Sin.h src/Function_Sqrt.h src/Function_Sum.h src/Function_Tan.h src/Function_Variable.h src/LIC.h src/Macros.h $(DISTDIR)/
	$(COPY_FILE) --parents shared/CallTracer.cpp shared/MessageLogger.cpp shared/StringHelper.cpp src/AbstractFunction.cpp src/Function_Constant.cpp src/Function_Cos.cpp src/Function_Difference.cpp src/Function_Exp.cpp src/Function_Exponent.cpp src/Function_Log.cpp src/Function_Product.cpp src/Function_Quotient.cpp src/Function_Sign.cpp src/Function_Sin.cpp src/Function_Sqrt.cpp src/Function_Sum.cpp src/Function_Tan.cpp src/Function_Variable.cpp src/LIC.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r LIC.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/moc_CallTracer.cpp build/moc_MessageLogger.cpp build/moc_StringHelper.cpp build/moc_AbstractFunction.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_CallTracer.cpp build/moc_MessageLogger.cpp build/moc_StringHelper.cpp build/moc_AbstractFunction.cpp
build/moc_CallTracer.cpp: shared/CallTracer.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QColor \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDate \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/QDomDocument \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/qdom.h \
		src/Deploy.h \
		../../../Qt/6.9.0/macos/libexec/moc
	@echo moc shared/CallTracer.h && /Users/shimaron/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/shimaron/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/shimaron/Documents/GitHub/LIC -I/Users/shimaron/Documents/GitHub/LIC/src -I/Users/shimaron/Documents/GitHub/LIC/shared -I/Users/shimaron/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtXml.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/shimaron/Qt/6.9.0/macos/lib shared/CallTracer.h -o build/moc_CallTracer.cpp

build/moc_MessageLogger.cpp: shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/libexec/moc
	@echo moc shared/MessageLogger.h && /Users/shimaron/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/shimaron/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/shimaron/Documents/GitHub/LIC -I/Users/shimaron/Documents/GitHub/LIC/src -I/Users/shimaron/Documents/GitHub/LIC/shared -I/Users/shimaron/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtXml.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/shimaron/Qt/6.9.0/macos/lib shared/MessageLogger.h -o build/moc_MessageLogger.cpp

build/moc_StringHelper.cpp: shared/StringHelper.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QPair \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qpair.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/6.9.0/macos/libexec/moc
	@echo moc shared/StringHelper.h && /Users/shimaron/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/shimaron/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/shimaron/Documents/GitHub/LIC -I/Users/shimaron/Documents/GitHub/LIC/src -I/Users/shimaron/Documents/GitHub/LIC/shared -I/Users/shimaron/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtXml.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/shimaron/Qt/6.9.0/macos/lib shared/StringHelper.h -o build/moc_StringHelper.cpp

build/moc_AbstractFunction.cpp: src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/libexec/moc
	@echo moc src/AbstractFunction.h && /Users/shimaron/Qt/6.9.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201402L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=17 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/shimaron/Qt/6.9.0/macos/mkspecs/macx-clang -I/Users/shimaron/Documents/GitHub/LIC -I/Users/shimaron/Documents/GitHub/LIC/src -I/Users/shimaron/Documents/GitHub/LIC/shared -I/Users/shimaron/Qt/6.9.0/macos/lib/QtWidgets.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtGui.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtXml.framework/Headers -I/Users/shimaron/Qt/6.9.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/shimaron/Qt/6.9.0/macos/lib src/AbstractFunction.h -o build/moc_AbstractFunction.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/CallTracer.o: shared/CallTracer.cpp shared/CallTracer.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QColor \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDate \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/QDomDocument \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/qdom.h \
		src/Deploy.h \
		shared/StringHelper.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QPair \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qpair.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QUrl \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qurl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/CallTracer.o shared/CallTracer.cpp

build/MessageLogger.o: shared/MessageLogger.cpp shared/CallTracer.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QColor \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDate \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/QDomDocument \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/qdom.h \
		src/Deploy.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MessageLogger.o shared/MessageLogger.cpp

build/StringHelper.o: shared/StringHelper.cpp shared/CallTracer.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QColor \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qcolor.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDate \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDateTime \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/QDomDocument \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/qdom.h \
		src/Deploy.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		shared/StringHelper.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QPair \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qpair.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qregularexpression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/StringHelper.o shared/StringHelper.cpp

build/AbstractFunction.o: src/AbstractFunction.cpp src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Function_Constant.h \
		src/Function_Cos.h \
		src/Function_Difference.h \
		src/Function_Exp.h \
		src/Function_Exponent.h \
		src/Function_Log.h \
		src/Function_Product.h \
		src/Function_Quotient.h \
		src/Function_Sign.h \
		src/Function_Sin.h \
		src/Function_Sqrt.h \
		src/Function_Sum.h \
		src/Function_Tan.h \
		src/Function_Variable.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/AbstractFunction.o src/AbstractFunction.cpp

build/Function_Constant.o: src/Function_Constant.cpp src/Function_Constant.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Constant.o src/Function_Constant.cpp

build/Function_Cos.o: src/Function_Cos.cpp src/Function_Cos.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Cos.o src/Function_Cos.cpp

build/Function_Difference.o: src/Function_Difference.cpp src/Function_Difference.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Difference.o src/Function_Difference.cpp

build/Function_Exp.o: src/Function_Exp.cpp src/Function_Exp.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Exp.o src/Function_Exp.cpp

build/Function_Exponent.o: src/Function_Exponent.cpp src/Function_Exponent.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Exponent.o src/Function_Exponent.cpp

build/Function_Log.o: src/Function_Log.cpp src/Function_Log.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Log.o src/Function_Log.cpp

build/Function_Product.o: src/Function_Product.cpp src/Function_Product.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Product.o src/Function_Product.cpp

build/Function_Quotient.o: src/Function_Quotient.cpp src/Function_Quotient.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Quotient.o src/Function_Quotient.cpp

build/Function_Sign.o: src/Function_Sign.cpp src/Function_Sign.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Sign.o src/Function_Sign.cpp

build/Function_Sin.o: src/Function_Sin.cpp src/Function_Sin.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Sin.o src/Function_Sin.cpp

build/Function_Sqrt.o: src/Function_Sqrt.cpp src/Function_Sqrt.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Sqrt.o src/Function_Sqrt.cpp

build/Function_Sum.o: src/Function_Sum.cpp src/Function_Sum.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Sum.o src/Function_Sum.cpp

build/Function_Tan.o: src/Function_Tan.cpp src/Function_Tan.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Tan.o src/Function_Tan.cpp

build/Function_Variable.o: src/Function_Variable.cpp src/Function_Variable.h \
		src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Function_Variable.o src/Function_Variable.cpp

build/LIC.o: src/LIC.cpp src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/LIC.h \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/QDomElement \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/qdom.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		src/Macros.h \
		shared/MessageLogger.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QList \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QSet \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qset.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QString \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QFile \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QImage \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.9.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QTime \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/LIC.o src/LIC.cpp

build/main.o: src/main.cpp src/AbstractFunction.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qobject.h \
		src/LIC.h \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/QDomElement \
		../../../Qt/6.9.0/macos/lib/QtXml.framework/Headers/qdom.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QHash \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.9.0/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.9.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/moc_CallTracer.o: build/moc_CallTracer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_CallTracer.o build/moc_CallTracer.cpp

build/moc_MessageLogger.o: build/moc_MessageLogger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MessageLogger.o build/moc_MessageLogger.cpp

build/moc_StringHelper.o: build/moc_StringHelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_StringHelper.o build/moc_StringHelper.cpp

build/moc_AbstractFunction.o: build/moc_AbstractFunction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_AbstractFunction.o build/moc_AbstractFunction.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

